/* =========================================================================
   MYHitch Nexus — domain types
   -------------------------------------------------------------------------
   These mirror the shapes the real API is expected to return. Every screen
   reads them through lib/mock-api, so swapping the mock functions for fetch()
   calls later should not require touching component code.
   ========================================================================= */

export type ContentType =
  | "commercial"
  | "film"
  | "entertainment"
  | "education"
  | "news"
  | "documentary"
  | "live"
  | "tourism"
  | "government"
  | "nonprofit"
  | "user-generated"
  | "music"
  | "podcast";

/** Underlying asset format — orthogonal to `ContentType` (which is genre/vertical, not
 * format). `music`/`podcast` content types always carry `kind: "audio"`; every other
 * content type carries `kind: "video"`. Drives storage bucket, upload validation, the
 * upload wizard's branching, and which player component renders. */
export type MediaKind = "video" | "audio";

export type ContentStatus =
  | "draft"
  | "pending"
  | "published"
  | "scheduled"
  | "private"
  | "unlisted"
  | "restricted"
  | "rejected"
  | "archived";

export type AccessModel =
  | "free"
  | "ad-supported"
  | "rent"
  | "buy"
  | "subscription"
  | "ppv"
  | "membership";

export type AgeRating = "U" | "PG" | "12" | "15" | "18";

export type ChannelKind =
  | "creator"
  | "business"
  | "film-studio"
  | "education"
  | "government"
  | "nonprofit"
  | "news";

export type UserRole =
  | "viewer"
  | "creator"
  | "business"
  | "enterprise"
  | "advertiser"
  | "producer"
  | "education"
  | "organisation"
  // "admin" stays a valid UserRole value — it's still used as a generic actor-role label
  // throughout the mock/demo audit trail (AuditLogEntry.actorRole, unrelated to the real
  // account_roles table). It is NOT one of the three real, grantable admin tiers below —
  // see rbac.ts/the 20260923000001 migration, where "admin" was retired from
  // account_roles.role in favour of these three scoped ones.
  | "admin"
  | "moderator"
  | "finance-admin"
  | "super-admin";

export type LiveStatus = "upcoming" | "live" | "ended" | "replay" | "cancelled";

export type LiveAccessType =
  | "public"
  | "private"
  | "ticketed"
  | "subscriber-only"
  | "invitation-only";

export type CampaignStatus =
  | "draft"
  | "pending"
  | "active"
  | "paused"
  | "completed"
  | "rejected";

export type ModerationAction =
  | "approve"
  | "reject"
  | "request-changes"
  | "restrict"
  | "demonetise"
  | "geo-block"
  | "age-restrict"
  | "suspend"
  | "remove";

export type EntitlementReason =
  | "free"
  | "ad-supported"
  | "purchased"
  | "rented"
  | "subscription"
  | "membership"
  | "ticket"
  | "owner"
  | "preview"
  | "none";

export type PlaybackBlockReason =
  | "entitlement-required"
  | "geo-restricted"
  | "preview-limit"
  | "age-gate"
  | "unavailable";

export interface Money {
  /** Minor units (cents) so nothing ever hits float rounding. */
  amount: number;
  currency: "AUD" | "GBP" | "USD" | "EUR" | "LKR";
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  description: string;
  contentType: ContentType;
  /** Configurable from /admin/settings — proves categories are data, not code. */
  featured: boolean;
  videoCount: number;
  accentToken: 1 | 2 | 3 | 4 | 5 | 6;
  imageUrl?: string;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  languageCode: string;
  kind: "subtitles" | "captions" | "sdh" | "descriptions";
  autoGenerated?: boolean;
  status: "ready" | "generating" | "failed";
}

export interface AudioTrack {
  id: string;
  language: string;
  languageCode: string;
  kind: "original" | "dubbed" | "audio-description" | "commentary";
}

export interface QualityLevel {
  id: string;
  label: string;
  height: number;
  bitrateKbps: number;
}

export interface CreditEntry {
  role: string;
  name: string;
  character?: string;
}

export interface AffiliateCommerceLink {
  id: string;
  label: string;
  productName: string;
  price: Money;
  /** Mart catalogue reference if cross-linking is supported. */
  martProductId?: string;
  timestampSeconds?: number;
}

export interface VideoPricing {
  accessModels: AccessModel[];
  rentPrice?: Money;
  buyPrice?: Money;
  ppvPrice?: Money;
  rentalWindowHours?: number;
  membershipTier?: string;
  sponsored?: boolean;
  sponsorName?: string;
  affiliateLinks?: AffiliateCommerceLink[];
}

export interface VideoRights {
  declaredOwner: string;
  ownershipConfirmed: boolean;
  licenceStart: string;
  licenceEnd: string | null;
  /** ISO-3166 alpha-2. Empty array means worldwide. */
  permittedCountries: string[];
  blockedCountries: string[];
  ageRating: AgeRating;
  contentLabels: string[];
}

export interface Video {
  id: string;
  slug: string;
  title: string;
  synopsis: string;
  channelId: string;
  contentType: ContentType;
  /** Defaults to "video" for every seeded/pre-existing video — see `MediaKind`'s comment. */
  kind: MediaKind;
  categoryIds: string[];
  tags: string[];
  status: ContentStatus;
  /** "awaiting_transcode" for a real upload with no playable stream yet (real video
   * transcoding is still blocked on a Mux account) — "none" for every seeded/mock video. */
  processingStatus?: "none" | "awaiting_transcode";
  posterGradient: [string, string];
  thumbnailUrl?: string;
  heroUrl?: string;
  durationSeconds: number;
  releaseDate: string;
  publishedAt: string | null;
  scheduledFor: string | null;
  language: string;
  languageCode: string;
  country: string;
  productionCompany?: string;
  participants?: string[];
  credits: CreditEntry[];
  subtitles: SubtitleTrack[];
  audioTracks: AudioTrack[];
  qualities: QualityLevel[];
  hasAudioDescription: boolean;
  pricing: VideoPricing;
  rights: VideoRights;
  views: number;
  uniqueViewers: number;
  likes: number;
  ratingAverage: number;
  ratingCount: number;
  commentCount: number;
  watchTimeSeconds: number;
  completionRate: number;
  /** Series/season/episode assignment from the publishing step. */
  seriesId?: string;
  seriesTitle?: string;
  seasonNumber?: number;
  episodeNumber?: number;
  trailerAvailable: boolean;
  /** Local sample clip served from /public/media. Never a remote stream. */
  sampleSrc: string;
  watermarkEnabled: boolean;
}

export interface Channel {
  id: string;
  handle: string;
  name: string;
  kind: ChannelKind;
  tagline: string;
  about: string;
  verified: boolean;
  country: string;
  languages: string[];
  followers: number;
  totalViews: number;
  videoCount: number;
  joinedAt: string;
  bannerGradient: [string, string];
  avatarGradient: [string, string];
  avatarUrl?: string;
  bannerUrl?: string;
  links: Array<{ label: string; href: string }>;
  /** Organisation verification state, driven from /admin/organisations. */
  verificationStatus: "unverified" | "pending" | "verified" | "rejected";
  contactEmail: string;
}

export interface Series {
  id: string;
  channelId: string;
  title: string;
  description: string;
  seasons: Array<{
    number: number;
    title: string;
    episodeIds: string[];
  }>;
  posterGradient: [string, string];
  thumbnailUrl?: string;
}

export interface Playlist {
  id: string;
  channelId: string;
  title: string;
  description: string;
  visibility: "public" | "unlisted" | "private";
  videoIds: string[];
  updatedAt: string;
  posterGradient: [string, string];
  thumbnailUrl?: string;
}

/** A viewer's own, personal playlist — real from day one (viewerPlaylists.ts), distinct
 * from the creator-side channel `Playlist` above (a "series" a channel publishes). No
 * mock/legacy shape to bridge, since a personal playlist never existed for a viewer to
 * reach before this. */
export interface ViewerPlaylist {
  id: string;
  accountId: string;
  /** Real only — which household profile this playlist is private to, or null when it's
   * account-wide (visible to every profile on the account). */
  profileId: string | null;
  title: string;
  description: string | null;
  visibility: "public" | "unlisted" | "private";
  videoCount: number;
  createdAt: string;
  updatedAt: string;
  /** Only present when fetched scoped to a specific video (the "Save to playlist" modal's
   * checkbox state). */
  containsVideo?: boolean;
}

export interface Comment {
  id: string;
  videoId: string;
  authorName: string;
  authorHandle: string;
  authorGradient: [string, string];
  body: string;
  createdAt: string;
  likes: number;
  /** Whether the current viewer has liked this comment. */
  likedByMe?: boolean;
  pinned: boolean;
  heartedByCreator: boolean;
  status: "published" | "held" | "removed";
  heldReason?: string;
  replies: Array<Omit<Comment, "replies" | "videoId">>;
}

export interface Rating {
  videoId: string;
  userId: string;
  stars: 1 | 2 | 3 | 4 | 5;
  createdAt: string;
}

export interface LiveEvent {
  id: string;
  channelId: string;
  title: string;
  description: string;
  status: LiveStatus;
  accessType: LiveAccessType;
  scheduledStart: string;
  actualStart: string | null;
  endedAt: string | null;
  timezone: string;
  posterGradient: [string, string];
  thumbnailUrl?: string;
  viewerCount: number;
  peakViewers: number;
  price?: Money;
  streamKey: string;
  ingestUrl: string;
  chatEnabled: boolean;
  replayVideoId: string | null;
  replayPublished: boolean;
  categoryIds: string[];
}

export interface ChatMessage {
  id: string;
  liveEventId: string;
  authorName: string;
  authorAvatarUrl?: string;
  authorGradient: [string, string];
  body: string;
  sentAt: string;
  role: "viewer" | "moderator" | "host" | "subscriber";
  status: "visible" | "held" | "removed";
}

export interface Poll {
  id: string;
  liveEventId: string;
  question: string;
  options: Array<{ id: string; label: string; votes: number }>;
  status: "draft" | "open" | "closed";
}

export interface ViewerProfile {
  id: string;
  name: string;
  kind: "adult" | "child" | "teen";
  avatarGradient: [string, string];
  avatarUrl?: string;
  maxAgeRating: AgeRating;
  language: string;
  /** Mock/demo profiles only — real profiles never carry the actual PIN or its hash to
   * the client (see profilePin.ts); a real profile's PIN state is `hasPinSet` instead,
   * and verification always goes through verifyProfilePin() (a real server call, not a
   * client-side string comparison). */
  pinCode?: string | null;
  hasPinSet?: boolean;
  isKids?: boolean;
}

export interface User {
  id: string;
  name: string;
  email: string;
  handle: string;
  roles: UserRole[];
  activeRole: UserRole;
  country: string;
  language: string;
  avatarGradient: [string, string];
  avatarUrl?: string;
  emailVerified: boolean;
  mobileVerified: boolean;
  mfaEnabled: boolean;
  createdAt: string;
  status: "active" | "suspended" | "pending" | "closed";
  /** Real only — true for an account an admin created directly with a temporary
   * password that hasn't been changed yet (see adminUsers.ts's createAdminUser()). */
  mustChangePassword?: boolean;
  profiles: ViewerProfile[];
  activeProfileId: string;
  channelId?: string;
  notificationPreferences: Record<NotificationEvent, NotificationChannels>;
  parentalControls: {
    enabled: boolean;
    maxAgeRating: AgeRating;
    pin: string;
  };
  privacy: {
    watchHistoryVisible: boolean;
    watchlistPublic: boolean;
    personalisedRecommendations: boolean;
    personalisedAds: boolean;
  };
}

export type NotificationEvent =
  | "new-upload"
  | "live-starting"
  | "reply"
  | "mention"
  | "purchase-receipt"
  | "rental-expiring"
  | "payout"
  | "policy";

export interface NotificationChannels {
  email: boolean;
  push: boolean;
  inApp: boolean;
}

export interface AppNotification {
  id: string;
  event: NotificationEvent;
  title: string;
  body: string;
  createdAt: string;
  read: boolean;
  href: string;
}

export interface Entitlement {
  videoId: string;
  userId: string;
  granted: boolean;
  reason: EntitlementReason;
  blockReason?: PlaybackBlockReason;
  expiresAt?: string;
  previewSeconds?: number;
  /** Country the (mocked) request appears to originate from. */
  requestCountry: string;
}

export interface WatchProgress {
  videoId: string;
  positionSeconds: number;
  durationSeconds: number;
  updatedAt: string;
  completed: boolean;
  /** Real accounts only — true exactly once, the moment this account's watch of the
   * video first counted toward its view total. */
  viewCounted?: boolean;
}

export interface PurchaseRecord {
  id: string;
  /** Null for a plan purchase (a subscription invoice) — nothing to link to. */
  videoId: string | null;
  /** Only set for a real purchase — videoById() (mock-only lookup) can never resolve a
   * real video's id, so without this the purchases page would show a bare uuid instead
   * of a title. */
  videoTitle?: string;
  kind: "buy" | "rent" | "ppv" | "subscription" | "membership";
  price: Money;
  purchasedAt: string;
  expiresAt: string | null;
  status: "completed" | "refunded" | "expired" | "active";
  invoiceNumber: string;
  /** Stripe's own hosted receipt/invoice page — real accounts only. */
  receiptUrl?: string | null;
}

export interface Subscription {
  id: string;
  name: string;
  kind: "platform" | "channel-membership";
  /** Real-only (a mock/channel-membership row has no real plan id) — the single source
   * of truth for "which of the three paid platform tiers is this," e.g. gating
   * Family-only features. Never derive that from `name`/`id` string-matching: `name` is
   * just display copy (PLAN_DISPLAY[plan].name) and silently drifts from `plan` the
   * moment marketing copy changes, which is exactly what happened before this field
   * existed — found live 2026-09-24, an account with an active Business plan was told on
   * one page it had "an active Nexus Business Plan" and on another that it needed to
   * upgrade to unlock /business, because each page re-derived plan identity its own way. */
  plan?: "premium" | "family" | "business";
  channelId?: string;
  price: Money;
  interval: "monthly" | "annual";
  status: "active" | "cancelled" | "past-due";
  renewsAt: string;
  startedAt: string;
  benefits: string[];
  /** Real only — Stripe's cancel_at_period_end: still `status: "active"` (access
   * continues), but won't renew. The mock's cancelSubscription() flips status straight
   * to "cancelled" instead, so this only ever appears for a real subscription. */
  cancelAtPeriodEnd?: boolean;
}

/* ------------------------------- Upload -------------------------------- */

export type UploadPhase =
  | "idle"
  | "uploading"
  | "paused"
  | "failed"
  | "processing"
  | "complete";

export interface UploadSession {
  id: string;
  fileName: string;
  fileSizeBytes: number;
  uploadedBytes: number;
  phase: UploadPhase;
  /** Mock chunk index — the resumable UI resumes from here after a failure. */
  chunkIndex: number;
  totalChunks: number;
  error?: string;
  createdAt: string;
}

export interface ThumbnailSuggestion {
  id: string;
  label: string;
  gradient: [string, string];
  timestampSeconds: number;
  score: number;
}

export interface VideoDraft {
  uploadSessionId: string;
  kind: MediaKind;
  title: string;
  description: string;
  contentType: ContentType;
  categoryIds: string[];
  tags: string[];
  participants: string[];
  productionCompany: string;
  releaseDate: string;
  language: string;
  country: string;
  thumbnailId: string | null;
  customThumbnailName: string | null;
  /** Real, publicly-servable URL once a custom thumbnail has actually been uploaded to
   * storage (real channels only) — `customThumbnailName` stays display-only (the file's
   * original name), this is what the publish gate writes to `videos.thumbnail_url`. */
  customThumbnailUrl?: string | null;
  subtitles: SubtitleTrack[];
  autoTranscribe: boolean;
  audioDescription: boolean;
  rights: VideoRights;
  pricing: VideoPricing;
  status: ContentStatus;
  scheduledFor: string | null;
  playlistIds: string[];
  seriesId: string | null;
  seasonNumber: number | null;
  episodeNumber: number | null;
}

export interface BulkImportRow {
  id: string;
  fileName: string;
  title: string;
  contentType: ContentType;
  language: string;
  releaseDate: string;
  ageRating: AgeRating;
  accessModel: AccessModel;
  status: "ready" | "warning" | "error";
  message?: string;
}

/* ----------------------------- Advertising ------------------------------ */

export interface CampaignTargeting {
  countries: string[];
  languages: string[];
  ageBands: string[];
  interests: string[];
  categoryIds: string[];
  devices: string[];
}

export interface CampaignCreative {
  id: string;
  name: string;
  format: "pre-roll" | "mid-roll" | "post-roll" | "overlay" | "sponsored-card";
  durationSeconds: number;
  /** Mock/display-only placeholder colour — always present (synthesised for a real
   * creative too) so every existing gradient-box preview keeps rendering unchanged. */
  gradient: [string, string];
  /** Mock/display-only CTA caption — synthesised from clickThroughUrl for a real creative. */
  clickThroughLabel: string;
  /** Real fields, present only for a real (non-mock) creative. */
  assetUrl?: string | null;
  clickThroughUrl?: string | null;
  status: "approved" | "pending" | "rejected";
}

export interface Campaign {
  id: string;
  advertiserId: string;
  advertiserName: string;
  name: string;
  objective: "awareness" | "consideration" | "conversion" | "traffic";
  status: CampaignStatus;
  budget: Money;
  dailyCap: Money;
  spend: Money;
  /** The advertiser's set flat rate — real field (2026-09-25); replaces the discarded
   * mock-only "bidStrategy" UI state, which was collected but never sent anywhere. */
  cpm: Money;
  startDate: string;
  endDate: string;
  targeting: CampaignTargeting;
  creatives: CampaignCreative[];
  placements: string[];
  frequencyCap: { impressions: number; perHours: number };
  brandSafety: {
    excludedLabels: string[];
    minAgeRating: AgeRating;
    blockUserGenerated: boolean;
  };
  metrics: {
    impressions: number;
    completedViews: number;
    clicks: number;
    ctr: number;
    conversions: number;
    cpm: number;
  };
  createdAt: string;
  submittedAt: string | null;
}

export interface Lead {
  id: string;
  channelId: string;
  name: string;
  email: string;
  company: string;
  sourceVideoId: string;
  message: string;
  status: "new" | "contacted" | "qualified" | "closed";
  createdAt: string;
}

export interface ProductLink {
  id: string;
  channelId: string;
  productName: string;
  martProductId: string;
  price: Money;
  attachedVideoIds: string[];
  clicks: number;
  conversions: number;
  commissionRate: number;
}

/* ------------------------------ Analytics ------------------------------- */

export interface TimeSeriesPoint {
  date: string;
  views: number;
  watchHours: number;
  uniqueViewers: number;
  revenue: number;
}

export interface RetentionPoint {
  percent: number;
  audience: number;
}

export interface BreakdownSlice {
  label: string;
  value: number;
  share: number;
}

export interface CreatorAnalytics {
  channelId: string;
  range: AnalyticsRange;
  totals: {
    views: number;
    uniqueViewers: number;
    watchTimeSeconds: number;
    completionRate: number;
    averageViewDuration: number;
    subscribersGained: number;
    subscribersLost: number;
    revenue: Money;
  };
  deltas: {
    // null (real channels only): no prior-period baseline to compare against (it had
    // zero activity) — the stat is genuinely new, not a computed percentage. See
    // analytics.ts's pctChange() for why this is a distinct case from a real 0% change.
    views: number | null;
    watchTime: number | null;
    revenue: number | null;
    uniqueViewers: number | null;
  };
  timeSeries: TimeSeriesPoint[];
  retention: RetentionPoint[];
  trafficSources: BreakdownSlice[];
  countries: BreakdownSlice[];
  languages: BreakdownSlice[];
  devices: BreakdownSlice[];
  revenueByContent: Array<{
    videoId: string;
    title: string;
    revenue: number;
    views: number;
    model: AccessModel;
  }>;
  adPerformance: {
    impressions: number;
    fillRate: number;
    ecpm: number;
    revenue: number;
  };
  topVideos: Array<{
    videoId: string;
    title: string;
    views: number;
    watchHours: number;
    completionRate: number;
  }>;
}

export type AnalyticsRange = "7d" | "28d" | "90d" | "365d";

export interface RevenueSummary {
  channelId: string;
  currency: Money["currency"];
  available: number;
  pending: number;
  lifetime: number;
  nextPayoutDate: string;
  byStream: BreakdownSlice[];
  transactions: Array<{
    id: string;
    date: string;
    description: string;
    kind: "advertising" | "ad" | "rental" | "purchase" | "membership" | "ppv" | "tip" | "payout";
    gross: number;
    fee: number;
    net: number;
  }>;
}

/* -------------------------------- Admin --------------------------------- */

export interface ModerationItem {
  id: string;
  kind: "content" | "comment" | "live" | "copyright" | "channel" | "campaign";
  targetId: string;
  title: string;
  channelId: string;
  submittedAt: string;
  priority: "low" | "normal" | "high" | "urgent";
  queue: "pending-review" | "reported" | "copyright" | "live-incident" | "verification";
  reportReasons: string[];
  reportCount: number;
  status: "open" | "actioned" | "escalated" | "dismissed";
  assignedTo: string | null;
  notes: string;
}

export interface AuditLogEntry {
  id: string;
  actor: string;
  actorRole: UserRole;
  action: string;
  targetType: string;
  targetId: string;
  reason: string;
  createdAt: string;
  ip: string;
  severity: "info" | "notice" | "warning" | "critical";
}

export interface AdminUserRow {
  id: string;
  name: string;
  email: string;
  roles: UserRole[];
  status: User["status"];
  country: string;
  createdAt: string;
  lastActiveAt: string;
  channelId?: string;
  flags: number;
  /** Real only — true until an admin-created account signs in and sets its own
   * password. See adminUsers.ts's createAdminUser(). */
  mustChangePassword?: boolean;
}

export interface Organisation {
  id: string;
  name: string;
  kind: ChannelKind;
  registrationNumber: string;
  country: string;
  representative: string;
  representativeEmail: string;
  verificationStatus: Channel["verificationStatus"];
  submittedAt: string;
  documents: Array<{
    id: string;
    name: string;
    type: string;
    status: "received" | "verified" | "rejected";
    uploadedAt: string;
  }>;
  timeline: Array<{
    id: string;
    label: string;
    at: string;
    actor: string;
    state: "done" | "current" | "pending" | "failed";
  }>;
  channelId?: string;
}

export interface CaseNote {
  id: string;
  caseId: string;
  author: string;
  body: string;
  createdAt: string;
  kind: "note" | "escalation" | "resolution";
}

export interface AdminCase {
  id: string;
  reference: string;
  subject: string;
  domain: "legal" | "safety" | "payment" | "copyright";
  status: "open" | "investigating" | "escalated" | "resolved";
  priority: ModerationItem["priority"];
  openedAt: string;
  owner: string;
  relatedId: string;
  notes: CaseNote[];
}

export interface PlatformConfigTables {
  categories: Category[];
  contentLabels: Array<{
    id: string;
    label: string;
    severity: "info" | "warning" | "restricted";
    autoAgeGate: boolean;
  }>;
  pricingRules: Array<{
    id: string;
    name: string;
    model: AccessModel;
    minPrice: Money;
    maxPrice: Money;
    active: boolean;
  }>;
  commissions: Array<{
    id: string;
    scope: string;
    /** Real only — the raw scope key ("purchase_rental" | "ppv" | "membership") a real
     * edit needs to send back; `scope` itself is the display label. */
    scopeKey?: string;
    platformShare: number;
    creatorShare: number;
    effectiveFrom: string;
  }>;
  taxes: Array<{
    id: string;
    country: string;
    name: string;
    rate: number;
    appliesTo: string;
  }>;
  currencies: Array<{
    code: Money["currency"];
    name: string;
    symbol: string;
    rateToAud: number;
    enabled: boolean;
  }>;
  payoutRules: Array<{
    id: string;
    method: string;
    minimum: Money;
    schedule: string;
    holdDays: number;
    active: boolean;
  }>;
}

export interface AdminDashboardSummary {
  pendingContent: number;
  reportedContent: number;
  copyrightClaims: number;
  liveIncidents: number;
  verificationQueue: number;
  campaignsAwaitingApproval: number;
  activeLiveEvents: number;
  totalUsers: number;
  revenue30d: Money;
  payoutsDue: Money;
  trend: Array<{ date: string; reviews: number; reports: number }>;
}

export interface OrgPayoutSummary {
  organizationId: string;
  organizationName: string;
  connected: boolean;
  chargesEnabled: boolean;
  payoutsEnabled: boolean;
  detailsSubmitted: boolean;
  grossMinor: number;
  availableMinor: number;
  paidMinor: number;
  lastPayoutAt: string | null;
}

export interface AdminFinanceSummary {
  platform: { commission30dMinor: number; payoutsDueMinor: number; currency: string };
  trend: Array<{ date: string; grossMinor: number; commissionMinor: number }>;
  revenueByStream: Array<{ label: string; grossMinor: number }>;
  organizations: OrgPayoutSummary[];
  failedPayoutCount: number;
}

export interface PlatformAnalyticsSummary {
  range: AnalyticsRange;
  totals: {
    views: number;
    uniqueViewers: number;
    watchTimeSeconds: number;
    completionRate: number;
    averageViewDuration: number;
  };
  deltas: {
    views: number | null;
    watchTime: number | null;
    uniqueViewers: number | null;
  };
  timeSeries: Array<{ date: string; views: number; watchHours: number; uniqueViewers: number }>;
  topVideos: Array<{
    videoId: string;
    title: string;
    channelId: string;
    channelName: string;
    views: number;
    watchHours: number;
    completionRate: number;
  }>;
  topChannels: Array<{ channelId: string; channelName: string; views: number; watchHours: number }>;
  countries: Array<{ label: string; value: number; share: number }>;
  devices: Array<{ label: string; value: number; share: number }>;
  languages: Array<{ label: string; value: number; share: number }>;
}

/* ------------------------------- Search --------------------------------- */

export interface SearchFilters {
  query?: string;
  contentTypes?: ContentType[];
  categoryIds?: string[];
  languages?: string[];
  countries?: string[];
  accessModels?: AccessModel[];
  ageRatings?: AgeRating[];
  minDurationSeconds?: number;
  maxDurationSeconds?: number;
  releaseYearFrom?: number;
  releaseYearTo?: number;
  hasSubtitles?: boolean;
  freeOnly?: boolean;
  sort?: "relevance" | "popular" | "newest" | "rating" | "duration";
  channelId?: string;
  page?: number;
  pageSize?: number;
}

export interface SearchResult {
  items: Video[];
  total: number;
  page: number;
  pageSize: number;
  facets: {
    contentTypes: Array<{ value: ContentType; count: number }>;
    languages: Array<{ value: string; count: number }>;
    countries: Array<{ value: string; count: number }>;
    accessModels: Array<{ value: AccessModel; count: number }>;
  };
}

export interface HomeRail {
  id: string;
  title: string;
  subtitle?: string;
  href: string;
  kind: "poster" | "wide" | "live" | "continue";
  videos: Video[];
}

export interface FeaturedContent {
  hero: Video[];
  rails: HomeRail[];
}

/* ============================== Magazine ================================= */

export type MagazineStatus =
  | "draft"
  | "submitted"
  | "changes_requested"
  | "published"
  | "rejected"
  | "withdrawn";

export interface MagazineArticle {
  id: string;
  slug: string;
  aboutTitle: string;
  videoId: string | null;
  videoTitle: string | null;
  videoSlug: string | null;
  channelId: string | null;
  channelName: string | null;
  authorAccountId: string;
  authorName: string;
  title: string;
  dek: string | null;
  bodyHtml: string;
  isFilmmakerAnalysis: boolean;
  status: MagazineStatus;
  reviewerNotes: string | null;
  /** Set once Lens's own review reports a decision back — see
   * src/lib/server/lensIntegration.ts and the /api/integrations/lens/status webhook. */
  lensUrl: string | null;
  submittedAt: string | null;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/* ============================== Sponsorship ("Exchange Hub") ============= */

export type SponsorshipListingStatus =
  | "draft"
  | "submitted"
  | "changes_requested"
  | "published"
  | "rejected"
  | "withdrawn"
  | "closed";

// Closed, non-financial reward vocabulary — see the sponsorship_rewards migration's
// header for why there is deliberately no free-text "what the sponsor gets" field.
export const SPONSORSHIP_REWARD_TYPES = [
  "screen_credit",
  "logo_placement",
  "product_placement",
  "premiere_tickets",
  "social_mention",
  "official_sponsor_badge",
] as const;
export type SponsorshipRewardType = (typeof SPONSORSHIP_REWARD_TYPES)[number];

export const SPONSORSHIP_REWARD_LABELS: Record<SponsorshipRewardType, string> = {
  screen_credit: "Screen credit",
  logo_placement: "Logo placement",
  product_placement: "Product placement",
  premiere_tickets: "Premiere tickets",
  social_mention: "Social media mention",
  official_sponsor_badge: "Official sponsor badge",
};

export interface SponsorshipListing {
  id: string;
  slug: string;
  channelId: string;
  channelName: string;
  channelAvatarGradient: [string, string];
  createdByAccountId: string;
  authorName: string;
  videoId: string | null;
  videoTitle: string | null;
  projectName: string;
  pitchHtml: string;
  rewardTypes: SponsorshipRewardType[];
  status: SponsorshipListingStatus;
  reviewerNotes: string | null;
  submittedAt: string | null;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}
